### ISSUE TITLE
Cli bugfix

### ISSUE THREAD

**Issue by triccyx** [robotology/yarp-device-ultrapython#12]
Some minor problems on the application should be resolved:
- [ ] The application crash on exit
- [ ] The application log extra information from the yarp library that should be hidden (I think it is possibile)
- [x] The constructor of the class UltraPythonCli should be empty as the grabber pointer is used through the new method UltraPythonCli::getGrabber

**Comment by mfussi66** [comment]
Regarding the second point, The yarp logging prints are caused by the device openings. Therefore, I'm not sure if the cli app can be modified to suppress yarp logs. 

However, I took a look at the docs and found some useful info (see Configuration): http://www.yarp.it/git-master/yarp_logging.html

" It is possible to change this by using (environment variable) YARP_QUIET to change the minimum level to [WARNING],"

Or maybe we could forward the logging towards the yarplogger, by running the app with "yarprun --log <app>".

**Comment by triccyx** [comment]
Thanks, @mfussi66 for the hint! Regarding the second point, I tried with YARP_QUIET, YARP_DEBUG_ENABLE, YARP_DEBUG_LOG_ENABLE.
The situation is better but still, some logs are printed. Quite strange.
